### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by ikegami**
- Switched from hv_store+strlen to more efficient and less error-prone hv_stores when possible.
- Switched from hv_fetch+strlen to more efficient and less error-prone hv_fetchs when possible.
- Speed up internal_recv by preallocating a string of the correct size for the body.
- Switched from "(SV*)expr" to error-checking "MUTABLE_SV(expr)".
- Switched from "(AV*)expr" to error-checking "MUTABLE_AV(expr)".
- Switched from "(HV*)expr" to error-checking "MUTABLE_HV(expr)".

### CODE REVIEW

**Comment by manchicken** [comment]
This looks great! Could you add a test for a body which would span multiple frames so we could make sure that this doesn't break that case? That's the only thing I worry about with this change, but it looks amazing. 

Thanks for your pull request.

**Comment by ikegami** [comment]
Will do

**Comment by ikegami** [comment]
Do you know how large it had to be to be split?

**Comment by ikegami** [comment]
The requested test has been added.

**Comment by manchicken** [comment]
This looks good. @markwellis, thoughts?

**Pull request merged**
