### PR TITLE
Connection issue

### PR DESCRIPTION
**Pull request by markwellis**
so the connection problem was because there was some data in the buffer, so i clear it on connect. we might want to move the error handling to one place, and do it when we close the socket. but that requires discussion and identification of potential issues

the rest is 
* a small doc improvment around ssl and SIGPIPE
* travis ssl mode
* and a l made the heartbeat test longer, for a more reliable test

### CODE REVIEW

**Comment by markwellis** [comment]
i have no idea why the coverage decreased, but it'll be a configuration issue with the ssl tests probably

**Comment by manchicken** [comment]
I think that the error thing with data in the pipe is similar to that issue
I opened about a year ago. I think we found it was a dependency issue.

**Comment by markwellis** [comment]
@manchicken "I think we found it was a dependency issue" - I'm not sure what you mean?

**Comment by manchicken** [comment]
Librabbitmq-c has this problem where they leave error messages on the wire
between calls I believe.

**Comment by markwellis** [comment]
That makes sense. We need to look at the error handling and make sure we're doing it in a consistent manner, which we're not at the moment

**Pull request merged**
