### PR TITLE
Add support for immediate return in recv()

### PR DESCRIPTION
**Pull request by marmand**
Will allow to have recv() that will wait infinitely and recv(0) wait 0ms.

### CODE REVIEW

**Comment by markwellis** [comment]
i'm a little confused as to how much use waiting 0ms is, i guess it's for when you know you have a message and you want it immediately? in which case would ->get not be a better choice?

**Comment by marmand** [comment]
Waiting 0ms is not waiting at all. This possibility is exposed by rabbitmq-c library and is totaly hidden by your module.

Having this possibility in recv is for when you're not sure whether you have a message and it's not vital to retrieve the message. Making some reading deamons not block on RabbitMQ reading but on other maybe more fundamentally critic paths.

**Comment by markwellis** [comment]
is that not the same as using get? https://metacpan.org/pod/Net::AMQP::RabbitMQ#get-channel-queuename-options

not that i'm against the change, i'm just cautious about changing existing behaviour. perhaps if using -1 instead of 0 to signify not to wait?

**Comment by marmand** [comment]
It is almost the same, an advantage of recv over get is that you already setted your consume. Meaning that when using the one or the other you're not thinking exactly the same way. And you do not have to pass the same arguments again (because on other places I do have timeouts that matters)

I agree that changing an existing behaviour is not great, but thinking this again
I put 0 or nothing it wait infinitely
I put -1 it doesn't wait
I put any n > 0, it waits n ms.

Against
I put undef it wait infinitely
I put any n >= 0, it waits at least n ms.

Putting them side by side shows that even by now the behaviour is not fully logic. Why is 0 a synonym of infinity ? That is a mathematical nonsense.

**Comment by markwellis** [comment]
It is nonsense, you're right. I've no idea why it's like that, but that's
my problem, I *really* dislike changing documented api's without a very
very good reason, e.g. it was totally broken before and it's the *only* way
to fix it.

Other than that, I now see the benefits of a none-waiting recv, so I'm all
for that.

So while -1 doesn't make any sense, it doesn't break existing behaviour,
and it's not that crazy semantically, as you can't have a negative wait, so
it returns instantly.

**Comment by manchicken** [comment]
Yeah, the Perl module right now tries to imitate the behavior of the api it
is wrapping. What you're doing could be better done with an alarm in your
Perl program.

It is very strange to me to have a blocking call take a time for waiting
when alarm seems like the better mechanism for that.

**Comment by zbentley** [comment]
I strongly recommend against using `alarm()`. Since there's only one global alarm per-process, any Perl that happens to use `alarm()` and wraps a call to an alarm-using-recv would malfunction. This is unintuitive and somewhat scary behavior. Truthiness/0/-1 discussions aside, the right way to implement timeout behavior on sockets is to use socket timeouts (via `select()` etc.), not alarms.

**Comment by marmand** [comment]
I totally understand that changing a documented API is not something we should do without any consideration for the existing code. I would like to make two more points before you do the final decision of whether I must move to the -1 solution or we move the documented API.

Net::AMQP::RabbitMQ is not yet in V1, that may as well mean that the documented API may change for better choices made with more knowledge added to the project. 0 being an alias to no argument I think the probability of having most users of recv(0) using only recv without any parameter is pretty high against the usage of explicitly saying 0 for infinity waiting. This behaviour being unchanged we could use an API change deprecation of using 0 as infinite value, creating a warning on 0 use that could be disabled with a temporary extra parameter or environment variable.

The underlying library allows to specify a 0 timeout to pass to poll(2), and in that case even avoid some operations. The idea in broking the API, even if unpleasant, would be to have a cleaner mapping between the perl package and the librabbitmq used underneath.

Do you prefer that I change to -1 or that we add temporary warnings during the API change ?

**Comment by markwellis** [comment]
I prefer -1, for a few reasons, 1, it's easier for me! 2, things will continue to just work for people who upgrade without thought, 3, we keeps compatibility with net::rabbitmq, although I'm not sure how true that is anymore, since we've diverged a lot since the initial fork.

As for using alarm, it doesn't seem right to me, and one of the tests already does this and i'm 95% sure it doesn't work, due to the block being way down in the c library, but that could be fixed already, so maybe not.

Using select also seems wrong, since it's doing stuff to the raw socket, which lib-rabbitmq wraps for us.
And since librabbitmq will let us have a 0ms timeout, then using that seems the most sensible to me, it's just a shame the docs explicitly said "If you do not provide a timeout (or set it to 0), then this call will block until it receives a message.", if it hadn't it would have been fine. but we can't change documented behaviour to the exact opposite, so in which case -1 seems like a reasonable middle ground.

Anyway, that's my 2 pence

**Comment by manchicken** [comment]
Alarm does work if you use posix sockets. I know because I did that at work
about a year ago.

**Comment by zbentley** [comment]
Alarm() is harmful in library code. It can be used if there's no alternative in top-level code, but in library code it destroys/overwrites any outer alarms that may have been set. Consider the following example (which uses sleep() instead of recv(), but a blocking system call is a blocking system call):

use v5.16;
    use warnings;

    sub fake_recv ($) {
        my ( $timeout ) = @_;
        local $SIG{ALRM} = sub {
            say "recv interrupted!";
        };
        alarm $timeout;
        sleep 5; # Simulates a receive.
    }

    # Application code that wants to enforce a timeout on some arbitrary operations that happen to include a receive-with-timeout call.
    sub slow_sub ($) {
        my ( $doreceive ) = @_;
        local $SIG{ALRM} = sub {
            say "application logic interrupted!";
        };
        alarm 5;
        if ( $doreceive ) {
            # Get a message with a 2 second timeout.
            my $fakemessage = fake_recv(2);
        }
        sleep 10; # Simulates doing some long application operation that should get interrupted.
    }

    my $t0 = time();
    slow_sub(1);
    say time() - $t0;

    $t0 = time();
    slow_sub(0);
    say time() - $t0;

    exit;


Library code should not, if it can help it, mutate unrelated global state on which other parts of the application depend.

Using `select`, `poll`, and friends (which is what librabbitmq uses internally) does not encounter this issue, as timeouts are handled on the socket itself rather than at the process level.

Note that this is a narrow criticism. In general, I tend to agree with using -1 as a stand-in value for "instant".

**Comment by manchicken** [comment]
Guys, $SIG{ALRM} is a safe signal. I'm talking posix signals.

Ultimately I think the idea of a blocking call having a provided timeout is
strange and in opposition to the concept of a blocking call.

**Comment by manchicken** [comment]
Btw, a safe signal in Perl will not play nice with a blocking system call
in C.

**Comment by manchicken** [comment]
http://perldoc.perl.org/perlipc.html#Deferred-Signals-(Safe-Signals)

**Comment by marmand** [comment]
@manchicken The issue is not to know whether alarm is a good way to implement the timeout or not, librabbitmq provides a recv that takes in a timeout, we are just using it here. Whether it is relevant to have timeouts in system calls is way out of scope of these proposed patches. The question here is whether we want to handle immediate returns from system-call as the underlying librabbitmq does or whether we do not want to break explicitly documented behaviour.

Moreover, the point of the patch is to allow the blocking call to be not blocking at all, I don't see a way of doing that with alarm.

**Comment by markwellis** [comment]
again, -1 for turning a blocking call into nonblocking makes sense in my mind. i'd be against it, but since librabbitmq provides this functionality, and we just wrap it, makes sense to me. if it wasn't for the original api/docs, i'd be fine with 0 being 0ms as well

**Comment by manchicken** [comment]
I'm okay with wrapping it as existing functionality. I don't think we
should do anything more than that though.

**Comment by manchicken** [comment]
I'm pretty sure the C library is just using alarm to implement the timeout.
I agree we should be true to the library we are wrapping, though.

**Comment by marmand** [comment]
The underlying is not using alarm. From what I am aware of, it is really uncommon to use alarm to handle timeouts when you have a system call that handles that for you.

https://github.com/alanxz/rabbitmq-c/blob/e324e5af0cc1d58f381fc0769f020b23748df71f/librabbitmq/amqp_socket.c#L579

Being true to the underlying library would be to have 0 meaning don't wait and undef being wait infinity. @markwellis is for the opposite proposal, avoiding to change the API currently documented behaviour.

**Comment by manchicken** [comment]
I stand corrected! :-)

My thoughts are that we should be as true to the api as possible, but I
don't want to break existing apps by changing the calling conventions.

**Comment by markwellis** [comment]
so, -1?

**Comment by manchicken** [comment]
Yeah, I'm a -1 on this one. I think get() gives us what we want here.

**Comment by manchicken** [comment]
Sorry, I lost context in my brain on this. Yes, argument is -1 for no wait
(I think that's the right context). Sorry for answering email from the
playground with my kids.

**Comment by marmand** [comment]
Hello, what is the status of this pull request ? Do you want me to do more dev on this feature ?

**Comment by markwellis** [comment]
sorry @marmand, i keep forgetting. Yes, if you could change it so 0 does what it does now, and -1 returns immediately, then I'll merge it and get it released :)

**Comment by marmand** [comment]
I already did in in commit 7a79fb32a1df56308454c16d7847dfdd5aff0897

**Comment by markwellis** [comment]
Sorry I didn't see that! I'll merge and release tomorrow morning. Thanks
Armand :)

**Comment by DavsX** [comment]
Btw I'm already using this patch in a soon-to-be-production system (under testing on a stage system atm) and so far it is performing OK.

**Comment by markwellis** [comment]
this will be in version 1.00100, which should be on cpan shortly

**Pull request merged**
