### PR TITLE
11 uselongdouble

### PR DESCRIPTION
**Pull request by markwellis**

### CODE REVIEW

**Comment by markwellis** [comment]
it feels like cheating. but i can't find a way to make it work. it seems to be the way other people have solved this issue.

floats in rabbitmq are double, and in perl long double. i wouldn't have thought that would cause loss of precision, because there's more bits. unless i'm not understanding it right.

tl;dr it fixes the test, but i don't think it's right

**Comment by manchicken** [comment]
I don't think long double is portable, you may have to do something like we did for int64.

**Comment by markwellis** [comment]
I reckon so. I'm just confused as to how moving a double from c to a long double in perl causes loss of precision. It doesn't make sense.

I think I might be missing what uselongdouble does. Time to go and read the perl source code for a bit I guess

**Comment by markwellis** [comment]
I've come to the conclusion that it's because of rounding, and changing the numbers is the right fix.

Although I will add a note to the docs stating that if you're using -Duselongdouble then your numbers may come out "funny"

Using the below with a "normal" perl and a uselongdouble perl, it's easy to see how the numbers are really represented, and in uselongdouble  perl is rounding further out, but in a way that makes the number not round back to 1.2.

```perl
use Devel::Peek;

use Inline C => Config =>
    BUILD_NOISY => 0;

use Inline C => <<'EOC';

void foo() {
    double x = 12;
    double y = 10;
    double foo = x / y;

    printf("c f %.100f\n", foo);

    long double xl = 12;
    long double yl = 10;
    long double foo_long = xl / yl;
    printf("c Lf %.100Lf\n", foo_long);
}

EOC

foo();

print sprintf "perl f %.100f\n", (12/10);
print sprintf "perl Lf %.100Lf\n", (12/10);
```

Do you think it's acceptable to add a note to the docs saying you should check your floating point precision if you're using uselongdouble because AMQP uses doubles and not long doubles, so you should round according to your needs

If so, then it's also acceptable that we change our test data to a number that can accurately be represented by floats, and thus doesn't lose any precision.

**Comment by manchicken** [comment]
There's a module for long double: https://metacpan.org/pod/Math::LongDouble though it doesn't have the convenient C functions that `Math::UInt64` had.

Documentation may be a useful way to do this, but this is really for header types, yeah? I'm okay just doing this for headers.

**Pull request closed without merging**
