### PR TITLE
RabbitMQ: force utf8 for props headers

### PR DESCRIPTION
**Pull request by DavsX**
As of [issue 69](https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/issues/69)

### CODE REVIEW

**Comment by markwellis** [comment]
seems this has broken the tests :(

**Comment by DavsX** [comment]
Seems like queue binding/unbinding headers need to be utf8 as well. (new PR for consideration)

**Comment by markwellis** [comment]
looking better. can we get some tests checking that this works as expected for none utf8 locales?

or maybe it'd be better as an option, instead of something that is done all the time.

@manchicken  what are your thoughts?

**Comment by DavsX** [comment]
How would that work as an option? Would it be inside the Net::AMQP::RabbitMQ object itself ( A little problematic since we return an amqp_connection_something struct there )? Or as an optional parameter for example on publish? In that case you would have to specify `options` and `props` to be able to define the force_utf8 flag at the end. Or could it be a global variable, which would be set inside ->new()? Like `my $mq = Net::AMQP::RabbitMQ->new(force_header_utf8 => 1)`?

**Comment by markwellis** [comment]
a global variable, which would be set inside ->new() sounds reasonable to me, but it might be quite inflexible. is there a time when you'd want to force utf8 headers in some cases but not others? if so, it wouldn't really work that well, but we can cross that bridge when we come to it - if we ever do.

otherwise an option in `options` would be a good idea, but `queue_bind` and `queue_unbind` don't have `options`. adding options wouldn't be hard, just odd as the parameter order would be different to everything else. but mostly i dislike this as it seems like it would be confusing to users to have to specify force_utf8 in several places, and it wouldn't be that clear.

so i'm thinking an option passed to `new` would be best, and as long as it's documented that if it's on it's on, then i think that would be ok. besides at a later date we can always make and interface to twiddle it if need be

but that said, @manchicken knows this stuff better, and reading comment https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/issues/69#issuecomment-145194143 i guess that's along the lines of what he was saying

**Comment by manchicken** [comment]
This doesn't seem based on a property, it just seems to hardcode all header value strings to be UTF8.

**Comment by manchicken** [comment]
I also think this should be on a per publish basis, not on the constructor, and not a global.

**Comment by manchicken** [comment]
As you said before, this should be a publish property, sent with delivery
mode and the like.

**Comment by markwellis** [comment]
i'll go with @manchicken then as he knows more about this stuff!

**Comment by DavsX** [comment]
With publish we could have a special key inside `options` or `props`. What about queue_bind/unbind? There is no `options` argument atm.

**Comment by manchicken** [comment]
What about queue_bind/unbind? I thought we were talking about basic.publish
calls.

**Comment by DavsX** [comment]
If I just force_utf8 only in the publish function, then the queue bind test hangs and fails (not sure about the reason yet)

**Comment by manchicken** [comment]
I'd need to see how you were implementing it.

**Comment by DavsX** [comment]
https://github.com/DavsX/net-amqp-rabbitmq/commit/ad13eb511dfcf4707e90a655f426860ffb7cd893  this was the first commit

**Comment by manchicken** [comment]
So, why is there a problem with making it so that the utf8 forcing in the `publish()`.

**Comment by DavsX** [comment]
The tests were failing for some reason. https://travis-ci.org/net-amqp-rabbitmq/net-amqp-rabbitmq/builds/83461792 When I set force_utf8 for queue_bind/unbind as well, they passed. I did not investigate it furhter.

**Comment by manchicken** [comment]
It looks like you're just turning on forcing UTF-8 for everything.

**Comment by DavsX** [comment]
As far as headers go, yes. It is still a suggestion, not sure if it is the best solution. The only thing I know is that sending non-utf8 string as AMQP_FIELD_KIND_BYTES (type 'x') is not compatible with some libraries (as it is not part of the AMQP specs).

**Comment by manchicken** [comment]
Are you joining us Sunday? Let's hash this out then.

**Comment by DavsX** [comment]
What's on Sunday?

**Comment by markwellis** [comment]
We're having a virtual hackathon!

**Comment by manchicken** [comment]
Our hackathon.

**Comment by manchicken** [comment]
See #78, I think that is more along the lines of what I was thinking of.

Some people may already depend on the legacy behavior of strings in headers, and non-reserved headers do not have a defined type in the spec, so I don't think we should change this behavior by default.

**Comment by DavsX** [comment]
Passing the force_utf8 in publish options looks great. Soon I'll be able to switch from a manual-tweaked Net::AMQP::RabbitMQ build to the official one (this was badly needed @work) :) good job!

**Comment by markwellis** [comment]
This is already released @DavsX

**Pull request closed without merging**
