### PR TITLE
Fix for Issue #142: Problem with Binary data · 

### PR DESCRIPTION
**Pull request by pmorch**
* Document why and how to use `content_type => 'binary'` for binary data in RabbitMQ.pm perldoc
* Test cases
    * Update test cases in t/*.t to use Use `content_type => 'binary'` instead of 'C' to follow RFC-2045
    * Split two t/*.t test cases into subtests for clearer code and output
    * Add testcases using `JSON::encode_json` and [@chamarreddy's sample_pack test case](https://github.com/net-amqp-rabbitmq/net-amqp-rabbitmq/issues/142#issuecomment-259040974)

### CODE REVIEW

**Comment by pmorch** [comment]
This fixes #142. (Perhaps clear from the title, but it is required in a comment for the github linking to work).

**Comment by manchicken** [comment]
Sorry for the delay, I moved and it completely screwed up my schedule.

For this, are you sure the `content_type` is the right field for that RFC? There's a `content_encoding` field, and I'm wondering if that's helpful here.

If we've found a UTF-8 encoding problem, that's one thing, but if I remember that RFC the encoding is more along the lines of what you're looking for.

I've written tests in the past where I transmitted binary executables as binary data with `application/octet-stream`, and they've come across just fine.

**Review by manchicken — COMMENTED** [review]
I'm not sure I understand what you're saying here. I've used `JSON::encode_json()` for RMQ here a bunch. 

Would you be able to chat about this so we can discuss?

**Comment by pmorch** [comment]
I must admit: I've since left that job and am no longer programming in perl. I seem to remember that we had a problem with binary data, but i don't remember the details.

I also seem to remember that the tests sent binary data inconsistently, which (I think) I attended to fix.

If this doesn't make sense to you feel free to close it. I no longer have an itch to scratch.

**Pull request closed without merging**
